const now = () => new Date().toISOString();

export const db = {
  users: [
    {
      id: "user-1",
      name: "Phulkeshwar Mahto",
      email: "phulkeshwar@example.com",
      password: "password123",
      role: "user",
      membership: "Gold",
      createdAt: now(),
    },
    {
      id: "admin-1",
      name: "GramBazaar Admin",
      email: "admin@grambazaar.in",
      password: "Admin@123",
      role: "admin",
      membership: "Platinum",
      createdAt: now(),
    },
  ],
  products: [
    {
      id: "prod-1",
      slug: "organic-wild-honey",
      name: "Organic Wild Honey",
      category: "Pantry",
      price: 399,
      originalPrice: 499,
      description: "Raw forest honey with a floral finish and zero heat processing.",
      specifications: {
        Weight: "500g",
        Origin: "Jharkhand",
        Processing: "Raw",
      },
      images: [
        {
          url: "https://images.unsplash.com/photo-1587049352851-8d4e89133924?auto=format&fit=crop&w=900&q=80",
          publicId: "honey-1",
          alt: "Organic wild honey jar",
        },
      ],
      emoji: "🍯",
      badge: "sale",
      inStock: true,
      stockCount: 24,
      rating: 4.8,
      reviewCount: 124,
      tags: ["raw", "honey", "forest"],
      isFeatured: true,
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "prod-2",
      slug: "darjeeling-green-tea",
      name: "Darjeeling Green Tea",
      category: "Beverages",
      price: 249,
      originalPrice: null,
      description: "Light, floral first-flush tea sourced from Darjeeling estates.",
      specifications: {
        Weight: "50g",
        Cups: "25",
        Flush: "First Flush",
      },
      images: [
        {
          url: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=900&q=80",
          publicId: "tea-1",
          alt: "Cup of green tea",
        },
      ],
      emoji: "🍵",
      badge: "new",
      inStock: true,
      stockCount: 30,
      rating: 4.7,
      reviewCount: 88,
      tags: ["tea", "green tea", "darjeeling"],
      isFeatured: true,
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "prod-3",
      slug: "cold-pressed-olive-oil",
      name: "Olive Oil Extra Virgin",
      category: "Pantry",
      price: 549,
      originalPrice: 649,
      description: "Single-origin extra virgin olive oil with low acidity and rich aroma.",
      specifications: {
        Volume: "500ml",
        Acidity: "< 0.5%",
        Origin: "Rajasthan",
      },
      images: [
        {
          url: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=900&q=80",
          publicId: "oil-1",
          alt: "Olive oil bottle",
        },
      ],
      emoji: "🫒",
      badge: "sale",
      inStock: true,
      stockCount: 18,
      rating: 4.6,
      reviewCount: 95,
      tags: ["olive oil", "cold pressed"],
      isFeatured: false,
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "prod-4",
      slug: "bamboo-dish-brush",
      name: "Bamboo Dish Brush",
      category: "Home",
      price: 189,
      originalPrice: null,
      description: "Biodegradable bamboo brush with natural sisal bristles.",
      specifications: {
        Material: "Bamboo + Sisal",
        Length: "28cm",
        Pack: "Single",
      },
      images: [
        {
          url: "https://images.unsplash.com/photo-1616627457211-92bfdf76f27b?auto=format&fit=crop&w=900&q=80",
          publicId: "brush-1",
          alt: "Bamboo dish brush",
        },
      ],
      emoji: "🪥",
      badge: "new",
      inStock: true,
      stockCount: 40,
      rating: 4.2,
      reviewCount: 46,
      tags: ["home", "bamboo", "kitchen"],
      isFeatured: false,
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "prod-5",
      slug: "neem-turmeric-soap",
      name: "Neem & Turmeric Soap",
      category: "Personal Care",
      price: 220,
      originalPrice: null,
      description: "Gentle handcrafted soap with neem and turmeric for daily care.",
      specifications: {
        Weight: "100g",
        Skin: "All Types",
        FreeFrom: "SLS, Parabens",
      },
      images: [
        {
          url: "https://images.unsplash.com/photo-1607006483225-53dbf6577722?auto=format&fit=crop&w=900&q=80",
          publicId: "soap-1",
          alt: "Neem soap bars",
        },
      ],
      emoji: "🧼",
      badge: null,
      inStock: true,
      stockCount: 50,
      rating: 4.4,
      reviewCount: 59,
      tags: ["soap", "neem", "turmeric"],
      isFeatured: false,
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "prod-6",
      slug: "ashwagandha-ksm66",
      name: "Ashwagandha KSM-66",
      category: "Health",
      price: 499,
      originalPrice: 599,
      description: "Clinically studied KSM-66 capsules for stress and stamina support.",
      specifications: {
        Count: "60 capsules",
        Dose: "500mg",
        Type: "Veg",
      },
      images: [
        {
          url: "https://images.unsplash.com/photo-1576671081837-49000212a370?auto=format&fit=crop&w=900&q=80",
          publicId: "capsules-1",
          alt: "Capsule supplement bottle",
        },
      ],
      emoji: "💊",
      badge: "sale",
      inStock: true,
      stockCount: 15,
      rating: 4.7,
      reviewCount: 72,
      tags: ["ashwagandha", "supplements"],
      isFeatured: true,
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "prod-7",
      slug: "copper-water-bottle",
      name: "Copper Water Bottle",
      category: "Home",
      price: 599,
      originalPrice: null,
      description: "Pure copper bottle crafted for everyday Ayurvedic hydration.",
      specifications: {
        Volume: "1L",
        Material: "Copper",
        Cap: "Leak-proof",
      },
      images: [
        {
          url: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=80",
          publicId: "copper-1",
          alt: "Copper bottle",
        },
      ],
      emoji: "🥤",
      badge: null,
      inStock: true,
      stockCount: 22,
      rating: 4.7,
      reviewCount: 63,
      tags: ["copper", "bottle", "home"],
      isFeatured: false,
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "prod-8",
      slug: "moringa-leaf-powder",
      name: "Moringa Leaf Powder",
      category: "Health",
      price: 329,
      originalPrice: null,
      description: "Sun-dried moringa powder packed with micronutrients and fiber.",
      specifications: {
        Weight: "200g",
        Form: "Fine Powder",
        ShelfLife: "18 months",
      },
      images: [
        {
          url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80",
          publicId: "moringa-1",
          alt: "Moringa powder bowl",
        },
      ],
      emoji: "🌿",
      badge: null,
      inStock: true,
      stockCount: 28,
      rating: 4.5,
      reviewCount: 41,
      tags: ["moringa", "powder", "health"],
      isFeatured: false,
      createdAt: now(),
      updatedAt: now(),
    },
  ],
  reviews: [
    {
      id: "review-1",
      productId: "prod-1",
      userId: "user-1",
      name: "Ananya S.",
      rating: 5,
      title: "Best raw honey",
      body: "Balanced sweetness and a rich floral aroma. This has become our everyday breakfast staple.",
      media: [],
      isApproved: true,
      createdAt: now(),
    },
    {
      id: "review-2",
      productId: "prod-2",
      userId: "user-1",
      name: "Rajesh K.",
      rating: 4,
      title: "Fresh and light",
      body: "Lovely cup with a clean finish. Packaging could be better, but the tea itself is excellent.",
      media: [],
      isApproved: true,
      createdAt: now(),
    },
  ],
  carts: {
    "user-1": [
      {
        productId: "prod-1",
        quantity: 1,
      },
    ],
  },
  orders: [
    {
      id: "ORD-8472",
      userId: "user-1",
      createdAt: "2026-04-15T10:00:00.000Z",
      items: [
        { productId: "prod-1", name: "Organic Wild Honey", price: 399, quantity: 1, emoji: "🍯" },
        { productId: "prod-3", name: "Olive Oil Extra Virgin", price: 549, quantity: 1, emoji: "🫒" },
      ],
      shippingAddress: {
        name: "Phulkeshwar Mahto",
        phone: "9999999999",
        line1: "72 Market Road",
        city: "Ranchi",
        state: "Jharkhand",
        pincode: "834001",
      },
      payment: {
        method: "cod",
        status: "paid",
      },
      subtotal: 948,
      shippingFee: 0,
      discount: 0,
      couponCode: "",
      total: 948,
      status: "Delivered",
      statusHistory: [
        { status: "Processing", updatedAt: "2026-04-15T10:00:00.000Z", note: "Order confirmed" },
        { status: "Delivered", updatedAt: "2026-04-18T14:00:00.000Z", note: "Delivered" },
      ],
    },
  ],
  coupons: [
    { code: "GRAM10", discountType: "percent", discountValue: 10, minOrderAmount: 500 },
    { code: "SAVE20", discountType: "percent", discountValue: 20, minOrderAmount: 1200 },
    { code: "FIRST50", discountType: "flat", discountValue: 50, minOrderAmount: 299 },
  ],
};

export const findUserById = (id) => db.users.find((user) => user.id === id);
export const findProductById = (id) => db.products.find((product) => product.id === id);
